use_frameworks!

platform :ios, '10.0'

target 'ObjCException_Example' do
  pod 'ObjCException', :path => '../'

  target 'ObjCException_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
